export const CATEGORIES: Array <{title : string, engtitle: string, id: number}> =[
	{  title:'سینما' ,                 engtitle: "cinema",             id : 2      },
	{  title:"برنامه های تلویزیونی" ,  engtitle: "TV",                 id : 3      },
	{  title:"ادبیات" ,                engtitle: "literature",         id : 4      },
	{  title:"موسیقی" ,                 engtitle: "music",              id : 6      },
	{  title:"تاریخ" ,                  engtitle: "history",            id : 9      },
	{  title:"زبان انگلیسی",            engtitle: "english",            id : 10     },
	{  title:"تکنولوژی" ,               engtitle: "technology",         id : 12     },
	{  title:"علم و دانش" ,             engtitle: "science",            id : 13     },
	{  title:"جغرافیا" ,                engtitle: "geography",          id : 17     },
	{  title:"فرهنگ و هنر" ,            engtitle: "art",                id : 20     },
	{  title:"بازیهای کامپیوتری" ,      engtitle: "computer_game",      id : 22     },
	{  title:"اطلاعات عمومی" ,           engtitle: "general_knowledge",  id : 23     },
	{  title:"ورزشی" ,                  engtitle: "sport",              id : 29     },
	{  title:"طبیعت" ,                  engtitle: "nature",             id : 41     },
	{  title:"مذهبی" ,                  engtitle: "religious",          id : 88     },
	{  title:"ریاضی و هوش" ,            engtitle: "math",               id : 139    },
	{  title:"لوگو و سرگرمی" ,          engtitle: "logo",               id : 140    },
	{  title:"غذا و نوشیدنی" ,          engtitle: "food",               id : 141    },
	{  title:"فوتبال" ,                engtitle: "football",           id : 142    },
]

export const CATEGORIES_bool: Array <{title : string, engtitle: string, id: number, checked: boolean}> =[
	{  title:' سینما' ,                 engtitle: "cinema",             id : 2     ,	checked : true },
	{  title:" برنامه های تلویزیونی" ,  engtitle: "TV",                 id : 3     ,	checked : true },
	{  title:" ادبیات" ,                engtitle: "literature",         id : 4     ,	checked : true},
	{  title:"موسیقی" ,                 engtitle: "music",              id : 6     ,	checked : true },
	{  title:"تاریخ" ,                  engtitle: "history",            id : 9     ,	checked : true },
	{  title:"زبان انگلیسی",            engtitle: "english",            id : 10    ,	checked : true },
	{  title:"تکنولوژی" ,               engtitle: "technology",         id : 12    ,	checked : true },
	{  title:"علم و دانش" ,             engtitle: "science",            id : 13    ,	checked : true },
	{  title:"جغرافیا" ,                engtitle: "geography",          id : 17    ,	checked : true },
	{  title:"فرهنگ و هنر" ,            engtitle: "art",                id : 20    ,	checked : true },
	{  title:"بازیهای کامپیوتری" ,      engtitle: "computer_game",      id : 22    ,	checked : true },
	{  title:"اطلاعات عمومی" ,           engtitle: "general_knowledge",  id : 23    ,	checked : true },
	{  title:"ورزشی" ,                  engtitle: "sport",              id : 29    ,	checked : true },
	{  title:"طبیعت" ,                  engtitle: "nature",             id : 41    ,	checked : true },
	{  title:"مذهبی" ,                  engtitle: "religious",          id : 88    ,	checked : true },
	{  title:"ریاضی و هوش" ,            engtitle: "math",               id : 139   ,	checked : true },
	{  title:"لوگو و سرگرمی" ,          engtitle: "logo",               id : 140   ,	checked : true },
	{  title:"غذا و نوشیدنی" ,          engtitle: "food",               id : 141   ,	checked : true },
	{  title:"فوتبال " ,                engtitle: "football",           id : 142   ,	checked : true },
]

export const CATEGORIES_bool_false: Array <{title : string, engtitle: string, id: number, checked: boolean}> =[
	{  title:' سینما' ,                 engtitle: "cinema",             id : 2     ,	checked : false },
	{  title:" برنامه های تلویزیونی" ,  engtitle: "TV",                 id : 3     ,	checked : false },
	{  title:" ادبیات" ,                engtitle: "literature",         id : 4     ,	checked : false},
	{  title:"موسیقی" ,                 engtitle: "music",              id : 6     ,	checked : false },
	{  title:"تاریخ" ,                  engtitle: "history",            id : 9     ,	checked : false },
	{  title:"زبان انگلیسی",            engtitle: "english",            id : 10    ,	checked : false },
	{  title:"تکنولوژی" ,               engtitle: "technology",         id : 12    ,	checked : false },
	{  title:"علم و دانش" ,             engtitle: "science",            id : 13    ,	checked : false },
	{  title:"جغرافیا" ,                engtitle: "geography",          id : 17    ,	checked : false },
	{  title:"فرهنگ و هنر" ,            engtitle: "art",                id : 20    ,	checked : false },
	{  title:"بازیهای کامپیوتری" ,      engtitle: "computer_game",      id : 22    ,	checked : false },
	{  title:"اطلاعات عمومی" ,           engtitle: "general_knowledge",  id : 23    ,	checked : false },
	{  title:"ورزشی" ,                  engtitle: "sport",              id : 29    ,	checked : false },
	{  title:"طبیعت" ,                  engtitle: "nature",             id : 41    ,	checked : false },
	{  title:"مذهبی" ,                  engtitle: "religious",          id : 88    ,	checked : false },
	{  title:"ریاضی و هوش" ,            engtitle: "math",               id : 139   ,	checked : false },
	{  title:"لوگو و سرگرمی" ,          engtitle: "logo",               id : 140   ,	checked : false },
	{  title:"غذا و نوشیدنی" ,          engtitle: "food",               id : 141   ,	checked : false },
	{  title:"فوتبال " ,                engtitle: "football",           id : 142   ,	checked : false },
]
